Add sql scripts and diagrams
VRublevski/video-converter pull request #1
Opened 2021-01-28 15:12 UTC by VRublevski

2021-02-01 09:06 UTC, papahmsolo requested changes
1. Estimation
2. ER diagram
3. Status table, Format table + table fields
4. UUID PK
5. DB scripts: create a separate schema, don't delete the DB if it exists, employ `IF NOT EXISTS`

2021-02-03 13:32 UTC, papahmsolo requested changes
This looks very good, Vlad!

- Let's use the `text` type instead of `varchar` in `schema.sql`, otherwise, it looks good.
- You'll need more SQL queries for your services, e.g. create the user. Add all the missing ones.

2021-02-03 13:32 UTC, papahmsolo commented on README.md
> + ```
Add the user parameter to this command, I'll only have the admin (`postgres`) user after installation

2021-02-03 13:32 UTC, papahmsolo commented on scripts/schema.sql
> +);
New line?

2021-02-10 15:30 UTC, VRublevski commented on scripts/schema.sql
> +);
@papahmsolo I don't know how she got here.

2021-02-15 08:13 UTC, papahmsolo approved these changes
Me like!

2021-02-15 08:13 UTC, merged