Add routing and validation of requests
VRublevski/video-converter pull request #3
Opened 2021-02-19 10:33 UTC by VRublevski

2021-02-19 13:23 UTC, papahmsolo requested changes
- don't panic in code
- is `iota` really needed along with Marshal/Unmarshal
- think of the responses bodies for all services

2021-02-19 13:23 UTC, papahmsolo commented on web/web.go
> +}
```
func userSignUp(w http.ResponseWriter, r *http.Request) {
	type request struct {
		login string
		pasw  string
	}
	 
	var usr user.User                           //request
	err := json.NewDecoder(r.Body).Decode(&usr) //decode helper
	defer r.Body.Close()

	if err != nil {
		respondErr(w, http.StatusBadRequest, err)
		return
	}

	isValid, err := usr.Validate()
	if !isValid {
		respondErr(w, http.StatusBadRequest, err)
		return
	}

	respond(w, 201, "created account") //decode helper
}
```

2021-02-21 20:07 UTC, VRublevski commented on web/web.go
> +}
@papahmsolo I added the response helpers, now the code is easier to read. As for panic I check for all possible values of the type in `switch` cases, so it will not trigger a crash.  I always thought that it's a good practice. The idea behind the `iota` and constants is to provide a type for those constants and engage the type system and the compiler, so that it can spot some programmer's mistakes. I believe that it's very productive to convert runtime bugs in compile time errors. I think that this particular case is too simple, but I just want to use this opportunity for practice.

2021-02-22 07:06 UTC, papahmsolo commented on web/web.go
> +}
I understand the concept of `iota` but we actually need the value of the status in our program. So making it a string would simplify things quite a bit. We also shouldn't be using things for the sake of using them, but rather when they are really needed. As one of the Go proverbs says, "Clear is better than clever", the simpler the code is the better.

2021-02-22 07:37 UTC, papahmsolo requested changes
Looks good!

Let's fix some stuff

2021-02-22 07:37 UTC, papahmsolo commented on web/web.go
> +}
We can validate this request too, can't we?

2021-02-22 07:37 UTC, papahmsolo commented on pkg/video/video.go
> +}
We can combine this into one method

2021-02-22 07:37 UTC, papahmsolo commented on web/web.go
> +}
Maybe we can put it into `response` package?

2021-02-22 07:37 UTC, papahmsolo commented on pkg/format/format.go
> +	}
Don't panic, it's not a good practice

2021-02-22 09:52 UTC, VRublevski commented on web/web.go
> +}
@papahmsolo Yes, I misunderstood the process of authentication.

2021-02-22 09:57 UTC, VRublevski commented on pkg/video/video.go
> +}
@papahmsolo I missed this when I was changing my code. Now I validate two fields: name and format and I lived this helper function as it is, because of testing convenience.

2021-02-22 10:00 UTC, VRublevski commented on pkg/format/format.go
> +	}
@papahmsolo Now I see a bigger picture of this and understand why I should not do it in this particular case.

2021-02-22 10:51 UTC, VRublevski commented on web/web.go
> +}
@papahmsolo I think that the issue and conversation did me good. Now I understand that one should weigh complexity and benefits that the complexity may provide. I deleted these constants.

2021-02-22 10:59 UTC, VRublevski commented on web/web.go
> +}
@papahmsolo I moved these functions to `util.go` .

2021-02-23 07:58 UTC, papahmsolo requested changes
Some thought for improvement:

- protocol package needs to be renamed
- comments to packages and functions
- utils -> respond and `error.go` could go there
- conversion request parameters

2021-02-24 08:57 UTC, papahmsolo requested changes
Let's improve this a little bit.

2021-02-24 08:57 UTC, papahmsolo commented on web/respond.go
> +}
- `json.NewEncoder(w).Encode(data)` 😃 
- what if `Encode` returns an error?

2021-02-24 08:57 UTC, papahmsolo commented on web/respond.go
> +}
We can call `respond` here

2021-02-24 08:57 UTC, papahmsolo commented on web/web.go
> +	}
Login can only return 401 as an error

2021-02-24 08:57 UTC, papahmsolo commented on web/web.go
> +	}
`{"Code":400,"Msg":"user: invalid password, validation: field does not fit in valid len ranges"}` what are these ranges?
`{"Code":400,"Msg":"user: invalid password, validation: the set of the fields's symbols is invalid"}` what are the valid symbols?

2021-02-24 08:57 UTC, papahmsolo commented on pkg/wish/request.go
> +package wish
I wish this package had a different name)

2021-02-24 14:52 UTC, VRublevski commented on web/respond.go
> +}
@papahmsolo I thought about that and I read an answer on Stackoverflow which says that if we have an error writing the response, we might not be able to write further the encountered error. Now I use different approach. I marshal `data` using `json` package in memory and then write it to the `ResponseWriter`.

2021-02-24 14:53 UTC, VRublevski commented on web/respond.go
> +}
@papahmsolo Yes, I missed that.

2021-02-24 14:55 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo I'll remember that.

2021-02-24 14:56 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo Now I send more descriptive error messages to the client.

2021-02-24 14:58 UTC, VRublevski commented on pkg/wish/request.go
> +package wish
@papahmsolo Whatever you want)

2021-02-25 07:07 UTC, papahmsolo reviewed
Looks good

2021-02-25 07:11 UTC, papahmsolo approved these changes

2021-02-25 07:12 UTC, merged