Add support for persisting the data
VRublevski/video-converter pull request #4
Opened 2021-02-24 06:53 UTC by VRublevski

2021-02-25 08:54 UTC, papahmsolo requested changes
Looks good!

2021-02-25 08:54 UTC, papahmsolo commented on cmd/main.go
> +	passwd := os.Args[2]
config

2021-02-25 08:54 UTC, papahmsolo commented on web/web.go
> +}
Server type?

2021-02-25 08:54 UTC, papahmsolo commented on web/web.go
> +	}
you can log `web` if you want

2021-02-25 08:54 UTC, papahmsolo commented on pkg/storage/storage.go
> +	ErrUnableToCreateUser = errors.New("storage: unable to create the user")
ErrUserAlreadyExists

2021-02-25 08:54 UTC, papahmsolo commented on pkg/storage/storage.go
> +}
Let's use a concrete type, for now, we'll get back to the interface for testing

2021-02-25 08:54 UTC, papahmsolo commented on pkg/storage/storage.go
> +}
handle duplication constraint error and other errors separatelly

2021-02-25 14:27 UTC, VRublevski commented on web/web.go
> +}
@papahmsolo I've changed the struct's type to `Server`.

2021-02-25 14:27 UTC, VRublevski commented on cmd/main.go
> +	passwd := os.Args[2]
@papahmsolo Now I use a configuration file for that.

2021-02-25 14:28 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo You're right. It looks reasonable after I thought about it for a while.

2021-02-25 14:30 UTC, VRublevski commented on pkg/storage/storage.go
> +	ErrUnableToCreateUser = errors.New("storage: unable to create the user")
@papahmsolo I've started to use more specific error messages, but the do not reflect the entity the statement operates on.

2021-02-25 14:31 UTC, VRublevski commented on pkg/storage/storage.go
> +}
@papahmsolo I've made it.

2021-02-25 14:33 UTC, VRublevski commented on pkg/storage/storage.go
> +}
@papahmsolo That is the case now.

2021-03-01 08:09 UTC, papahmsolo requested changes
Looks good, let's fix some issues

2021-03-01 08:09 UTC, papahmsolo commented on pkg/storage/storage.go
> +	ErrNotFound = errors.New("the requested data is not found")
Let's create specific errors, like `ErrUserAlreadyExists` then you can read the code better in the handler

2021-03-01 08:09 UTC, papahmsolo commented on pkg/storage/storage.go
> +	ErrStorage = errors.New("something went wrong")
No need for this error, you can simply return `err` for all the other cases

2021-03-01 08:09 UTC, papahmsolo commented on pkg/storage/storage.go
> +}
Here we mix up DB interaction with persisting files in the storage and they are separate things. We'll get back to files later, let's just move this code out of this method for now.

2021-03-02 05:29 UTC, VRublevski commented on cmd/main.go
> +}
@papahmsolo I've considered that and changed my code to employ these libs.

2021-03-02 05:46 UTC, VRublevski commented on pkg/conversion/entity.go
> +}
@papahmsolo The first name for this `struct` was `Response`. I wanted to decouple package `storage` from package `web`, as I think that the `storage` package should not know anything about data presentation, e.g. forming the response. I do not understand this moment a little bit. For me, it's the case that the lower layer package knows how it will be used by the upper layer package and uses data structures of the upper layer package. Also all of my SQL queries returns data that is ready to be sent to clients and I do not have to create functions that map the data returned by the queries to responses. So, I thought that I could use `Entity` name to decouple these packages at least on semantic level, because name `entity` is within the domain of `storage`.

2021-03-02 05:47 UTC, VRublevski commented on web/respond.go
>  	}
@papahmsolo I got rid of it.

2021-03-02 05:48 UTC, VRublevski commented on pkg/storage/storage.go
> +	ErrStorage = errors.New("something went wrong")
@papahmsolo Yes, I think that it's simpler and provides these same functionality.

2021-03-02 05:54 UTC, VRublevski commented on pkg/storage/storage.go
> +}
@papahmsolo I've removed this code.

2021-03-02 05:54 UTC, VRublevski commented on pkg/storage/storage.go
> +	ErrNotFound = errors.New("the requested data is not found")
@papahmsolo I've did that.

2021-03-02 08:56 UTC, papahmsolo requested changes
Looks good!

- Don't forget about `internal`
- Let's add hashing to use password

2021-03-02 08:56 UTC, papahmsolo commented on pkg/storage/storage.go
> +	ErrUserNotFound = errors.New("")
Forgot the error message

2021-03-02 08:56 UTC, papahmsolo commented on pkg/storage/storage.go
> +	return reports, nil
You can `return reports, rows.Err()`

2021-03-02 08:56 UTC, papahmsolo commented on pkg/storage/storage.go
> +}
- Not sure if we need a func for this, you'll make the same check in the calling func.
- "23505" could be a constant

2021-03-02 08:56 UTC, papahmsolo commented on cmd/main.go
> +	PostgrePassword string `split_words:"true"`
`required` tag

2021-03-02 08:56 UTC, papahmsolo commented on web/web.go
> +	}
```
err = s.storage.CreateUser(usr.Login, usr.Password)
	if err == storage.ErrUserAlreadyExists {
		respondErr(w, http.StatusConflict, fmt.Errorf("user with such login already exists"))
		return
	}
	if err != nil {
		respondErr(w, http.StatusInternalServerError, err)
		return
	}
```

2021-03-02 08:56 UTC, papahmsolo commented on pkg/storage/storage.go
> +	location := "/srv/http/videos/1"
get `location` as a func param

2021-03-02 08:56 UTC, papahmsolo commented on pkg/storage/storage.go
> +	row := s.db.QueryRow(insertVideo, name, location, format, userLogin)
`err = s.db.QueryRow(insertVideo, name, location, format, userLogin).Scan(&id)`

2021-03-02 18:29 UTC, VRublevski commented on pkg/storage/storage.go
> +	ErrUserNotFound = errors.New("")
@papahmsolo Sorry for that. I missed it.

2021-03-02 18:29 UTC, VRublevski commented on pkg/storage/storage.go
> +	return reports, nil
@papahmsolo That is neat.

2021-03-02 18:30 UTC, VRublevski commented on pkg/storage/storage.go
> +}
@papahmsolo You're are right in both of the cases.

2021-03-02 18:30 UTC, VRublevski commented on cmd/main.go
> +	PostgrePassword string `split_words:"true"`
@papahmsolo I've fixed that.

2021-03-02 18:32 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo I've made this change. Now this portion of code is less nested than it was before.

2021-03-02 18:33 UTC, VRublevski commented on pkg/storage/storage.go
> +	location := "/srv/http/videos/1"
@papahmsolo I pass `location` as parameter now.

2021-03-02 18:33 UTC, VRublevski commented on pkg/storage/storage.go
> +	row := s.db.QueryRow(insertVideo, name, location, format, userLogin)
@papahmsolo I've eliminated the variable.

2021-03-03 07:50 UTC, papahmsolo requested changes
Looks very good!

2021-03-03 07:50 UTC, papahmsolo commented on internal/storage/storage.go
> +	}
We can ignore checking this error as we don't need it in the handler

2021-03-03 07:50 UTC, papahmsolo commented on internal/storage/storage.go
> +	}
The query was unsuccessful, it's a server error

2021-03-03 07:50 UTC, papahmsolo commented on web/web.go
> +	hashedPasswd, err := bcrypt.GenerateFromPassword([]byte(usr.Password), 14)
Try `bcrypt.MinCost` instead of the magic constant

2021-03-03 08:47 UTC, VRublevski commented on internal/storage/storage.go
> +	}
@papahmsolo It's ignored now.

2021-03-03 08:47 UTC, VRublevski commented on internal/storage/storage.go
> +	}
@papahmsolo Yes, you are right.

2021-03-03 08:48 UTC, VRublevski commented on web/web.go
> +	hashedPasswd, err := bcrypt.GenerateFromPassword([]byte(usr.Password), 14)
@papahmsolo It worked like a charm.

2021-03-04 07:37 UTC, papahmsolo requested changes
Looks good!

As the name suggests `web.go` is probably not the best place for `persistFile` logic.
You can create a separate package for this, it will eventually be replace by cloud object storage.
Also let's first save the file to disk and then creating the appropriate records in the tables as we need to know the file ID for location

2021-03-04 07:37 UTC, papahmsolo commented on internal/storage/storage.go
> +		var report conversion.Report
Let's declare it outside the loop

2021-03-04 07:37 UTC, papahmsolo commented on internal/storage/storage.go
> +	return meta, nil
This block is the same as `return meta, err`

2021-03-04 07:37 UTC, papahmsolo commented on web/web.go
> +	location := path.Join("/", "srv", "http", "videos", uuid.NewString()+"."+vid.Format)
- `uuid.NewString()` could panic
- how about a plain string path?)

2021-03-04 07:37 UTC, papahmsolo commented on web/web.go
> +	}
don't forget to close the `f`

2021-03-04 07:38 UTC, papahmsolo approved these changes

2021-03-04 07:39 UTC, merged