Add jwt based authentication
VRublevski/video-converter pull request #8
Opened 2021-03-19 19:31 UTC by VRublevski

2021-03-25 07:17 UTC, papahmsolo requested changes
Looks good!

2021-03-25 07:17 UTC, papahmsolo commented on web/web.go
> +	router.HandleFunc("/videos/{videoId}", s.requireToken(s.getVideosByID)).Methods("GET")
We can apply auth middleware to protected routes only using a subrouter

2021-03-25 07:17 UTC, papahmsolo commented on web/web.go
> +	}
Look into `contextKey` type and methods to set and get it

2021-03-25 12:30 UTC, VRublevski commented on web/web.go
> +	router.HandleFunc("/videos/{videoId}", s.requireToken(s.getVideosByID)).Methods("GET")
@papahmsolo I use subrouters now.

2021-03-25 12:44 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo I've added a type for the login key.

2021-03-29 07:20 UTC, papahmsolo requested changes
Looks very good!

2021-03-29 07:20 UTC, papahmsolo commented on web/web.go
> +	token.Claims = claims
sc := jwt.StandardClaims{
		Subject: usr.Login,
		ExpiresAt: time.Now().Add(time.Hour * 72).Unix(),
	}

2021-03-29 07:20 UTC, papahmsolo commented on web/web.go
> +	}
```
	login, ok := LoginFromContext(r.Context())
	if !ok {
		respondErr(w, http.StatusInternalServerError, fmt.Errorf("unable to read the login"))
		return
	}
```

2021-03-29 07:20 UTC, papahmsolo commented on web/web.go
> +	authSubRouter.Use(s.requireToken)
Neat!

2021-03-29 08:30 UTC, VRublevski commented on web/web.go
> +	token.Claims = claims
@papahmsolo I've changed that. Now it does not depend on the specific name of a claim.

2021-03-29 08:34 UTC, VRublevski commented on web/web.go
> +	}
@papahmsolo Now it's less cluttered than before.

2021-03-29 08:38 UTC, VRublevski commented on web/web.go
> +	authSubRouter.Use(s.requireToken)
@papahmsolo yep :)

2021-03-29 09:14 UTC, papahmsolo approved these changes

2021-03-29 09:14 UTC, merged